---
deployment:
  tasks:
    - export DEPLOYPATH=$HOME/public_html/
    - /bin/cp -R * $DEPLOYPATH
    - cd $DEPLOYPATH
    - /bin/cp -n .env.example .env
    - chmod -R 775 storage bootstrap/cache
    - php artisan key:generate --force
    - php artisan config:clear
    - php artisan view:clear
    - php artisan optimize
