---
deployment:
  tasks:
    - export DEPLOYPATH=/home/USER/public_html/
    - /bin/cp -R * $DEPLOYPATH
    - /bin/cp .env.example $DEPLOYPATH.env
    - cd $DEPLOYPATH
    - /usr/local/bin/composer install
    - /usr/local/bin/php artisan migrate --force
    - /usr/local/bin/php artisan view:cache
    - /usr/local/bin/php artisan config:cache
